volumes:
  gitea:
#  keycloak_data:

networks:
  sso_network:
    driver: bridge

services:
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:22.0.1
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_HTTP_ENABLED=true
      - KC_SPI_NONCE_STORE_PROVIDER=disabled
    ports:
      - "8080:8080"
    volumes:
      - ./docker/keycloak/exports:/opt/keycloak/data/import
      - ./docker/keycloak/themes/multitenant:/opt/keycloak/themes/multitenant
    command: 
      - start-dev
      - --import-realm
    networks:
      - sso_network

  gitea:
    image: gitea/gitea:1.19
    container_name: gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - ROOT_URL=http://localhost:3000
      - OAUTH2_PROVIDER=openidConnect
      - OAUTH2_NAME=Keycloak
      - OAUTH2_AUTO_DISCOVER_URL=http://keycloak:8080/realms/gitea/.well-known/openid-configuration
      - OAUTH2_CLIENT_ID=gitea
      - OAUTH2_CLIENT_SECRET=your_client_secret
      - OAUTH2_USE_CUSTOM_URL=true
      - OAUTH2_TOKEN_URL=http://keycloak:8080/realms/gitea/protocol/openid-connect/token
      - OAUTH2_AUTH_URL=http://keycloak:8080/realms/gitea/protocol/openid-connect/auth
      - OAUTH2_SCOPES=openid email profile
    restart: always
    volumes:
      - ./gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3000:3000"
      - "22:22"
    networks:
      - sso_network
